### ISSUE TITLE
怎么修改封面制表时间

### ISSUE THREAD

**Issue by hi-zhenyu** [fatestigma/scuthesis#2]
封面上教务处制表下的时间怎么修改为当前时间啊

**Comment by fatestigma** [comment]
You can modify it in `scuthesis.cfg` file around line 35 with `\def\scu@jiaowuchu@date{二〇〇八年六月一日}`. Is this what you asked for?

你可以在 `scuthesis.cfg` 文件的第35行左右修改 `\def\scu@jiaowuchu@date{二〇〇八年六月一日}`。

**Comment by hi-zhenyu** [comment]
thank you!
