### ISSUE TITLE
请问如何使用etitle作为论文标题？

### ISSUE THREAD

**Issue by NeoFantom** [fatestigma/scuthesis#4]
如题。我将`scu@cover`中所有出现的`ctitle`都改成了`etitle`，但是却无法通过编译。我不太精通 latex，猜测也许是字体之类的问题。总之，能否麻烦学长帮忙看下如何使用`etitle`作为论文标题呢？

另，如果我直接把`ctitle`设置成英文，样式不统一不说，而且编译出来的题目一个单词占一行，整个标题占了七行。

**Comment by fatestigma** [comment]
不好意思，之前一忙就忘记回复了，如果想使用 `etitle` 的话，应该仅替换 `\scu@cover` 中的 `\scu@ctitle@value` 成 `\scu@etitle@value` 。
