### ISSUE TITLE
较长中文标题溢出封面题目行

### ISSUE THREAD

**Issue by ShreckYe** [fatestigma/scuthesis#6]
较长的中文标题在封面题目行会溢出，导致“题目”二字被遮盖。希望能通过调整换行解决。

**Comment by fatestigma** [comment]
不好意思，之前一忙就忘记回复了，这个确实是一个问题，一直没时间看，不知道你是否已经解决了，如果已经解决欢迎PR。

**Comment by feiLinX** [comment]
再次打扰了，请问这个问题解决了吗？按照README.pdf中加入~符号没有效果

**Comment by fatestigma** [comment]
如果我没记错，加入~的作用可能是中文摘要页的换行，而不是封面的。

封面的换行一直没时间弄，加上可能有四年没有写过macro了，可能需要一段时间。

**Comment by feiLinX** [comment]
现有一种解决方法，可用于中文标题仅稍稍长了一点的情况：将scuthesis.cls中大约于244行开始的代码替换为：
	\scu@ctitle@pre & \scu@underline[10cm]\scu@ctitle@value\\[1.16cm]
    \scu@cdepartment@pre & \scu@underline[10cm]\scu@cdepartment@value\\[1.16cm]
    \scu@cmajor@pre & \scu@underline[10cm]\scu@cmajor@value\\[1.16cm]
    \scu@cname@p  & \scu@underline[10cm]\scu@cname@value\\[1.16cm]
目的在于稍微增加underline的长度以适应标题。同样地，也需要将接下来的sid, session, csupervisor的underline长度作相应修改。
注意，该方法只适合题目仅仅稍长的情况（题目过长再应用此方法可能不符合排版要求）。

**Comment by fatestigma** [comment]
@feiLinX 你这个仅仅是增长了第二列的长度。

我刚刚看了一下代码，实际上封面是会换行的，在需要换行的位置加上空格即可。

```
\ctitle{四四四四四川大学本科科科科科科科科 生毕论文论文论文模板}
```

<img width="361" alt="Screen Shot 2020-04-26 at 12 28 11 AM" src="https://user-images.githubusercontent.com/3814129/80297826-d8a64780-8754-11ea-9282-2658e8315028.png">
